### ISSUE TITLE
License issue: MuPDF is GNU AGPL licensed

### ISSUE THREAD

**Issue by robinwatts** [joniks/Android-MuPDF#15]
MuPDF is released under the GNU AGPL. As such your code also needs to be licensed under the GNU APGL. You need to supply a copy of the license terms, and a pointer to where people can get the source from.

Please either do this, or take this repo down.

Thanks.

**Comment by joniks** [comment]
Done

**Comment by robinwatts** [comment]
Thanks, including the license is a great first step.

You also need to either include a copy of the source (not just the compiled binaries as you have done), or at least a pointer to where people can get the source from. If you made any changes to the libs as you built them, these must be made available too. Basically, people need to be able to recreate the compiled libraries that you include.

Thanks for making these changes.

**Comment by joniks** [comment]
Readme updated.

Thank you for the excellent work of your team.

**Comment by robinwatts** [comment]
Perfect. Thanks.
