### ISSUE TITLE
How to change theme colour?

### ISSUE THREAD

**Issue by adamhongmy** [joniks/Android-MuPDF#17]
The current theme colour is pink. How to change it?

**Comment by joniks** [comment]
Hi!

Color definitions here:
https://github.com/joniks/Android-MuPDF/blob/master/sample/res/values/colors.xml

All drawables in this folder:
https://github.com/joniks/Android-MuPDF/tree/master/sample/res

**Comment by adamhongmy** [comment]
Thanks for quick reply! It is really helpful! Thanks!
