### ISSUE TITLE
Can you tell me what the official version of the libmupdf.so file on the commit “joniks committed on 5 Aug 2015”

### ISSUE THREAD

**Issue by tjs4571** [joniks/Android-MuPDF#18]
Can you tell me what the official version of the libmupdf.so file 
on the commit “joniks committed on 5 Aug 2015”

thanks you so much

**Comment by joniks** [comment]
compiled libs: https://github.com/joniks/Android-MuPDF/commit/3c62f48eb3c87957c49a961044b938fe8a0c968a
compiled from this source commit: http://git.ghostscript.com/?p=mupdf.git;a=commit;h=61594159e15383f88ac856204aba1e014ef6e04d
