### ISSUE TITLE
Change default language

### ISSUE THREAD

**Issue by retsef** [joniks/Android-MuPDF#5]
There is a function in [LibraryUtils](https://github.com/joniks/Android-MuPDF/blob/master/library/src/com/artifex/mupdflib/LibraryUtils.java) that change the language and is set to "lv" by default. It need to be changed to this 
```java 
String lang = sharedPrefs.getString(PREF_APP_LANGUAGE, Locale.getDefault().getLanguage() );
```

**Comment by joniks** [comment]
Completed 5a8696f82a71bc5738fa7cd9f35c4d125553b6ac
